linters:
  enable:
    - govet
    - staticcheck
    - unused
    - typecheck
    - errcheck
    - ineffassign
    - gosimple
    - stylecheck
    - gocritic
    - goconst
    - gocyclo
    - gofmt
    - gosec
    - revive

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
  exclude-use-default: false
  exclude:
    - "error return value not checked.*"

linters-settings:
  gocyclo:
    max-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 2
  errcheck:
    exclude-functions:
      - fmt.Println
      - fmt.Printf
  staticcheck:
    checks: ["all"]
  revive:
    ignore-generated-header: true
    severity: warning
  gosec:
    exclude:
      - G104

output:
  format: colored-line-number
  print-issued-lines: true

severity:
  default-severity: warning
  error:
    - errcheck
    - gosec
